/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RIO.Watcher;

import java.io.IOException;

public class Watcher {
    private Server server = new Server();
    private int defualt_port = 5810;

    public Watcher() {
        try {
            server.start(defualt_port);
        } catch (IOException err) {
            err.printStackTrace();
        }
    }
}
