/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devsamuelv.rio.watcher;

import java.io.IOException;

public class Watcher {
    private Server server = new Server();
    private int defualt_port = 5810;
    private boolean streamStart = false;

    public Watcher() {
        try {
            server.start(defualt_port);
        } catch (IOException err) {
            err.printStackTrace();
        }
    }

    public String convertRowsToString(String[] rows) {
        StringBuilder builder = new StringBuilder();

        for (String s : rows) {
            builder.append(s);
        }

        return builder.toString();
    }

    public void record(String filename, String[] rows, String data) {
        if (!streamStart) {
            server.sendData("cmd:start");
            this.streamStart = true;
        }

        String strRows = convertRowsToString(rows);

        server.sendData("flr:" + filename + " dtr:[" + data + "] rws:[" + strRows + "]");
    }

    public void endConnection() {
        server.sendData("cmd:end-all");

        try {
            server.stop();
        } catch (IOException err) {
            err.printStackTrace();
        }
    }

    public void connect() {
        try {
            server.start(defualt_port);
        } catch (IOException err) {
            err.printStackTrace();
        }
    }
}
