/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devsamuelv.rio.watcher;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import com.devsamuelv.rio.watcher.Watcher;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Watcher classUnderTest = new Watcher();
        // assertTrue(classUnderTest.start(), "someLibraryMethod should return 'true'");
    }
}
